# softmax_classifier


In [1]:
import tensorflow as tf
tf.set_random_seed(777)

x_data = [[1, 2, 1, 1],
          [2, 1, 3, 2],
          [3, 1, 3, 4],
          [4, 1, 5, 5],
          [1, 7, 5, 5],
          [1, 2, 5, 6],
          [1, 6, 6, 6],
          [1, 7, 7, 7]]
y_data = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1],
          [0, 1, 0],
          [0, 1, 0],
          [0, 1, 0],
          [1, 0, 0],
          [1, 0, 0]]



/Users/koyo/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [7]:
X = tf.placeholder('float', [None, 4])
Y = tf.placeholder('float', [None, 3])

# 3가지를 가리는데 씀
nb_classes = 3

W = tf.Variable(tf.random_normal([4, nb_classes]), name='weight')
b = tf.Variable(tf.random_normal([nb_classes]), name='bias')

# tf.nn.softmax computes softmax activations
# softmax = exp(Logits) / reduce_sum(exp(Logits), dim) 

# lab-04-2-multi_variable_matmul_linear_regression.py
hypothesis = tf.nn.softmax(tf.matmul(X, W) + b)

# Simplified cost/loss function
cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis=1))

# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)
        


0 Cost:  134.62471 
Prediction:
 [[ -1.8817794    4.9310646    4.752573  ]
 [ -2.2687452    6.5826206    4.3913603 ]
 [  0.27750027  10.186381     6.3259325 ]
 [ -1.6933527   12.706827     7.176106  ]
 [-16.329416    18.445095    10.142345  ]
 [ -7.9923124   15.990015     4.335684  ]
 [-16.377577    19.8686       8.764169  ]
 [-19.593515    23.029886     9.808765  ]]
10 Cost:  133.54323 
Prediction:
 [[ -1.8676993   4.911497    4.743302 ]
 [ -2.247572    6.551512    4.376695 ]
 [  0.3058102  10.144287    6.3061132]
 [ -1.6547381  12.649275    7.149028 ]
 [-16.27339    18.368307   10.1062765]
 [ -7.9490876  15.928029    4.3067336]
 [-16.31829    19.786322    8.725597 ]
 [-19.524544   22.93428     9.763961 ]]
20 Cost:  132.47095 
Prediction:
 [[ -1.8536788   4.8920135   4.7340693]
 [ -2.2264943   6.520537    4.3620925]
 [  0.3339919  10.102374    6.2863793]
 [ -1.6162978  12.59197     7.122065 ]
 [-16.217596   18.29185    10.070359 ]
 [ -7.9060497  15.866305    4.2779064]
 [-16.259254   

380 Cost:  99.37278 
Prediction:
 [[ -1.3864406    4.243373     4.426468  ]
 [ -1.5272874    5.4896183    3.875908  ]
 [  1.2679113    8.707456     5.629418  ]
 [ -0.34271634  10.684857     6.224546  ]
 [-14.356121    15.746084     8.874381  ]
 [ -6.475404    13.81161      3.3186464 ]
 [-14.291533    16.976664     7.4085617 ]
 [-17.16651     19.66955      8.2341175 ]]
390 Cost:  98.59058 
Prediction:
 [[ -1.3744493    4.2267437    4.418575  ]
 [ -1.5094326    5.4631968    3.863442  ]
 [  1.2917329    8.671706     5.6125755 ]
 [ -0.31023848  10.635981     6.201539  ]
 [-14.308288    15.680809     8.843712  ]
 [ -6.4387865   13.758938     3.294066  ]
 [-14.241025    16.906727     7.375781  ]
 [-17.107735    19.588287     8.196041  ]]
400 Cost:  97.815025 
Prediction:
 [[ -1.3625084    4.210186     4.410715  ]
 [ -1.4916581    5.4368887    3.8510294 ]
 [  1.3154461    8.63611      5.5958056 ]
 [ -0.27790785  10.5873165    6.1786304 ]
 [-14.26065     15.615814     8.813173  ]
 [ -6.402326 

750 Cost:  74.442635 
Prediction:
 [[ -0.9748361    3.6731298    4.1555586 ]
 [ -0.917598     4.5838823    3.4483893 ]
 [  2.0804548    7.4819794    5.05189   ]
 [  0.76481926   9.009493     5.435687  ]
 [-12.712038    13.507407     7.822416  ]
 [ -5.2219133   12.005545     2.4761527 ]
 [-12.557373    14.578265     6.284455  ]
 [-15.148455    16.882645     6.9284277 ]]
760 Cost:  73.87182 
Prediction:
 [[ -0.96457934   3.6589367    4.1488085 ]
 [ -0.9024966    4.5613475    3.437747  ]
 [  2.100554     7.4514904    5.0375156 ]
 [  0.7922077    8.967812     5.4160557 ]
 [-12.671006    13.451681     7.7962246 ]
 [ -5.190777    11.960598     2.4551954 ]
 [-12.514147    14.518568     6.2564754 ]
 [-15.0981455   16.813274     6.8959293 ]]
770 Cost:  73.30584 
Prediction:
 [[ -0.95436525   3.6448045    4.142087  ]
 [ -0.88746333   4.5389094    3.4271502 ]
 [  2.1205606    7.4211316    5.0232024 ]
 [  0.81946886   8.926311     5.3965077 ]
 [-12.630144    13.396189     7.7701454 ]
 [ -5.1597767

1140 Cost:  55.414173 
Prediction:
 [[ -0.60518074   3.1622522    3.912323  ]
 [ -0.3768065    3.7730653    3.0652728 ]
 [  2.799205     6.3849936    4.534516  ]
 [  1.743935     7.5098896    4.7291503 ]
 [-11.230915    11.501135     6.8793826 ]
 [ -4.1035194   10.387811     1.7222674 ]
 [-10.999149    12.42917      5.2773576 ]
 [-13.334671    14.385369     5.758701  ]]
1150 Cost:  55.00436 
Prediction:
 [[ -0.59647775   3.1502416    3.9065967 ]
 [ -0.36416912   3.7540119    3.056264  ]
 [  2.8159728    6.359216     4.522352  ]
 [  1.766768     7.474653     4.7125416 ]
 [-11.19598     11.4539585    6.8572035 ]
 [ -4.0772915   10.349781     1.7045563 ]
 [-10.962451    12.378639     5.2536798 ]
 [-13.291948    14.326651     5.731201  ]]
1160 Cost:  54.59802 
Prediction:
 [[ -0.58781135   3.1382823    3.9008949 ]
 [ -0.3515904    3.7350411    3.0472941 ]
 [  2.8326616    6.3335514    4.5102415 ]
 [  1.7894945    7.4395695    4.696006  ]
 [-11.161188    11.406983     6.8351197 ]
 [ -4.0511

1510 Cost:  42.34363 
Prediction:
 [[ -0.30632782   2.7503922    3.7157278 ]
 [  0.054075     3.1199887    2.7563071 ]
 [  3.3700066    5.50148      4.117441  ]
 [  2.5209627    6.302201     4.1597314 ]
 [-10.029157     9.883095     6.1185694 ]
 [ -3.2061982    9.08391      1.1153461 ]
 [ -9.73861     10.696241     4.465431  ]
 [-11.866955    12.371636     4.815714  ]]
1520 Cost:  42.0441 
Prediction:
 [[ -0.29887748   2.7401414    3.7108274 ]
 [  0.06472743   3.1037421    2.7486153 ]
 [  3.3840914    5.4795017    4.1070614 ]
 [  2.5401292    6.2721596    4.145561  ]
 [ -9.999137     9.8428135    6.0996246 ]
 [ -3.1839252    9.05146      1.1002525 ]
 [ -9.707174    10.653104     4.445222  ]
 [-11.830346    12.321508     4.792244  ]]
1530 Cost:  41.747097 
Prediction:
 [[ -0.2914585    2.729934     3.7059476 ]
 [  0.07533097   3.0875654    2.7409568 ]
 [  3.39811      5.457618     4.0967255 ]
 [  2.5592036    6.242248     4.131452  ]
 [ -9.96924      9.802704     6.080761  ]
 [ -3.16175

1770 Cost:  35.322536 
Prediction:
 [[ -0.12241876   2.497623     3.5947762 ]
 [  0.31553483   2.7195232    2.566626  ]
 [  3.7152596    4.959745     3.861487  ]
 [  2.9906301    5.56175      3.810371  ]
 [ -9.287083     8.889696     5.6513147 ]
 [ -2.6580076    8.283834     0.743366  ]
 [ -8.962438     9.632478     3.9671226 ]
 [-10.962958    11.135469     4.236999  ]]
1780 Cost:  35.082066 
Prediction:
 [[ -0.11573732   2.488452     3.5903826 ]
 [  0.32497084   2.704999     2.559743  ]
 [  3.7277       4.9400973    3.8522    ]
 [  3.0075483    5.5348973    3.7976966 ]
 [ -9.26008      8.853646     5.634355  ]
 [ -2.6381602    8.254808     0.72987807]
 [ -8.934231     9.593878     3.9490423 ]
 [-10.930102    11.090613     4.2160015 ]]
1790 Cost:  34.843624 
Prediction:
 [[ -0.10908413   2.4793196    3.5860076 ]
 [  0.3343618    2.6905375    2.5528889 ]
 [  3.74008      4.920535     3.8429537 ]
 [  3.0243838    5.50816      3.7850766 ]
 [ -9.23319      8.817751     5.6174684 ]
 [ -2.61

 [-10.24076     10.150741     3.7760983 ]]


/Users/koyo/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


(101, 16) (101, 1)
one_hot: Tensor("one_hot:0", shape=(?, 1, 7), dtype=float32)
reshape one_hot: Tensor("Reshape:0", shape=(?, 7), dtype=float32)
Instructions for updating:
Colocations handled automatically by placer.
Step:     0	Cost: 5.480	Acc: 37.62%
Step:   100	Cost: 0.806	Acc: 79.21%
Step:   200	Cost: 0.488	Acc: 88.12%
Step:   300	Cost: 0.350	Acc: 90.10%
Step:   400	Cost: 0.272	Acc: 94.06%
Step:   500	Cost: 0.222	Acc: 95.05%
Step:   600	Cost: 0.187	Acc: 97.03%
Step:   700	Cost: 0.161	Acc: 97.03%
Step:   800	Cost: 0.141	Acc: 97.03%
Step:   900	Cost: 0.124	Acc: 97.03%
Step:  1000	Cost: 0.111	Acc: 97.03%
Step:  1100	Cost: 0.101	Acc: 99.01%
Step:  1200	Cost: 0.092	Acc: 100.00%
Step:  1300	Cost: 0.084	Acc: 100.00%
Step:  1400	Cost: 0.078	Acc: 100.00%
Step:  1500	Cost: 0.072	Acc: 100.00%
Step:  1600	Cost: 0.068	Acc: 100.00%
Step:  1700	Cost: 0.064	Acc: 100.00%
Step:  1800	Cost: 0.060	Acc: 100.00%
Step:  1900	Cost: 0.057	Acc: 100.00%
Step:  2000	Cost: 0.054	Acc: 100.00%
[True] Prediction