In [14]:
import tensorflow as tf

x1_data = [73., 93., 89., 96., 73.]
x2_data = [80., 88., 91., 98., 66.]
x3_data = [75., 93., 90., 100., 70.]
y_data = [152., 185., 180., 196., 142.]

# placeholders for a tensor that will be always fed.
x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)
Y = tf.placeholder(tf.float32)

w1 = tf.Variable(tf.random_normal([1]), name='weight1')
w2 = tf.Variable(tf.random_normal([1]), name='weight2')
w3 = tf.Variable(tf.random_normal([1]), name='weight3')
b = tf.Variable(tf.random_normal([1]), name='bias')
hypo = x1 * w1 + x2 * w2 + x3 * w3 + b

# cost/loss function
cost = tf.reduce_mean(tf.square(hypo - Y))
# Minimize. Need a very small learning rate for this data set
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())
for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypo, train],
                                  feed_dict={x1: x1_data, x2: x2_data, x3: x3_data, Y: y_data})
    if step % 100 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  23516.299 
Prediction:
 [11.29517  23.682396 18.06744  22.237331 18.126446]
100 Cost:  5.944378 
Prediction:
 [147.42348 187.15141 179.21332 197.70515 142.78888]
200 Cost:  5.7430935 
Prediction:
 [147.49976 187.09985 179.23758 197.71582 142.72702]
300 Cost:  5.5519133 
Prediction:
 [147.57407 187.0496  179.26125 197.72606 142.6669 ]
400 Cost:  5.3703604 
Prediction:
 [147.64644 187.00066 179.28429 197.73586 142.60847]
500 Cost:  5.197892 
Prediction:
 [147.71698 186.953   179.3068  197.7453  142.5517 ]
600 Cost:  5.034023 
Prediction:
 [147.7857  186.90657 179.32872 197.75432 142.49657]
700 Cost:  4.8783255 
Prediction:
 [147.85268 186.86136 179.35013 197.76299 142.44298]
800 Cost:  4.730384 
Prediction:
 [147.91792 186.81732 179.371   197.77129 142.39091]
900 Cost:  4.5897636 
Prediction:
 [147.9815  186.77443 179.39134 197.77922 142.34035]
1000 Cost:  4.4560976 
Prediction:
 [148.04346 186.73264 179.4112  197.78682 142.29123]
1100 Cost:  4.328982 
Prediction:
 [148.10385 18

In [20]:
x_data = [[73., 80., 75.],
          [93., 88., 93.],
         [89., 91., 90.],
         [96., 98.,100.],
         [73., 66., 70.]]

y_data = [[152.],[185.],[180.],[196.],[142.]]

# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3,1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypo = tf.matmul(X, W) + b

cost = tf.reduce_mean(tf.square(hypo - Y))

optimizer = tf.train.GradientDescentOptimizer(learning_rate = 1e-5)
train = optimizer.minimize(cost)

sess = tf.Session()

sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypo, train], feed_dict={X: x_data, Y: y_data})
    if step % 1000 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  52044.707 
Prediction:
 [[-35.754463]
 [-68.703415]
 [-54.407673]
 [-60.741024]
 [-57.357616]]
1000 Cost:  65.24308 
Prediction:
 [[162.8532 ]
 [176.79941]
 [183.95895]
 [199.21933]
 [131.26984]]
2000 Cost:  38.04686 
Prediction:
 [[160.11151]
 [178.68063]
 [183.121  ]
 [198.59662]
 [133.75256]]
